using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Bohn_Van_HW4.Models
{
    public enum MovieRating {G, PG, PG13, R}
    public class Movie
    {
        //This number should be autogenerated???
        [Display(Name = "Movie ID")]
        public Int32 MovieID { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title")]
        public String Title { get; set; }

        [Required(ErrorMessage = "Email for studio is required")]
        [Display(Name = "Email Address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        public String EmailAddress { get; set; }

        //Should the datatype be string??
        [Required(ErrorMessage = "Phone Number for studio is required")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [DisplayFormat(DataFormatString = "{0:###-###-####}", ApplyFormatInEditMode = true)]
        public String PhoneNumber { get; set; }

        [Required(ErrorMessage = "Release Date Needed")]
        [DataType(DataType.Date,ErrorMessage ="Please enter a valid date")]
        [Display(Name = "Release Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }

        [Required(ErrorMessage = "Rating is required")]
        [Display(Name = "Rating")]
        public MovieRating MovieRating { get; set; }

       
        [Display(Name = "Special Release")]
        public Boolean SpecialRelease { get; set; }

        [Display(Name = "Notes")]
        public String Notes {get;set;}



    }
}
